# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 07:29
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('responsible', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ('name',),
                'db_table': 'assets_areas',
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=200)),
                ('entry_date', models.DateField(auto_now_add=True, null=True)),
                ('initial_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=11)),
                ('current_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=11)),
                ('is_depreciable', models.BooleanField(default=True)),
                ('foto', models.FileField(blank=True, null=True, upload_to=b'fotos/%Y/%m/%d')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='af.Area')),
            ],
            options={
                'ordering': ('entry_date', 'code'),
                'db_table': 'assets_assets',
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
            },
        ),
        migrations.CreateModel(
            name='AssetDepreciationDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=11)),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=11)),
                ('depreciated_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=11)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='af.Area')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='af.Asset')),
            ],
            options={
                'ordering': ('area', 'asset'),
                'db_table': 'assets_depreciationdetail',
                'verbose_name': 'Depreciation Detail',
                'verbose_name_plural': 'Depreciations Details',
            },
        ),
        migrations.CreateModel(
            name='AssetDepreciationTotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_before', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=11)),
                ('total_depreciated', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=11)),
            ],
            options={
                'ordering': ('date',),
                'db_table': 'assets_depreciationtotal',
                'verbose_name': 'Depreciation Total',
                'verbose_name_plural': 'Depreciation Totals',
            },
        ),
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=11)),
            ],
            options={
                'ordering': ('name',),
                'db_table': 'assets_types',
                'verbose_name': 'Type',
                'verbose_name_plural': 'Types',
            },
        ),
        migrations.AlterUniqueTogether(
            name='assettype',
            unique_together=set([('name',)]),
        ),
        migrations.AlterUniqueTogether(
            name='assetdepreciationtotal',
            unique_together=set([('date',)]),
        ),
        migrations.AddField(
            model_name='assetdepreciationdetail',
            name='depreciation_total',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='af.AssetDepreciationTotal'),
        ),
        migrations.AddField(
            model_name='asset',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='af.AssetType'),
        ),
        migrations.AlterUniqueTogether(
            name='area',
            unique_together=set([('name',)]),
        ),
        migrations.AlterUniqueTogether(
            name='assetdepreciationdetail',
            unique_together=set([('depreciation_total', 'asset')]),
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together=set([('code',)]),
        ),
    ]
